// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    cookieParser: '',
    cookieSecret: '',
    db: 'blog',
    host: 'localhost',
    root: __dirname,
    QnClient: {
      accessKey: '',
      secretKey: '',
      bucket: '',
      domain: ''
    },
    perPageBlogSize: 10,
    googleAuthKey: '',
    loginPwd: '',
    loginUserName: '',
    titles: {
      blog_bloglist: "Blog · QORA BLOG · Innovative From The Core",
      blog_perBlog: "QORA BLOG · Innovative From The Core",
      blog_post: "POST BLOG · Innovative From The Core",
      blog_view: "View · QORA BLOG · Innovative From The Core",
      blog_edit: "Edit · QORA BLOG · Innovative From The Core",
      cover: "Cover · QORA BLOG · Innovative From The Core",
      eachCover: "QORA BLOG · Innovative From The Core",
      postCover: "Post Cover · QORA BLOG · Innovative From The Core",
      editCover: "Edit Cover · QORA BLOG · Innovative From The Core",
      index: "QORA BLOG · Innovative From The Core",
      about: "QORA · Innovative From The Core",
      manage: "manage · QORA BLOG · Innovative From The Core",
      login: "login · QORA BLOG · Innovative From The Core",
      tags: "Tag · QORA BLOG · Innovative From The Core",
      eachTag: "QORA BLOG · Innovative From The Core"
    }
  };

}).call(this);

//# sourceMappingURL=settings.map
